services:
  kie-extended-services:
    image: docker.io/apache/incubator-kie-sandbox-extended-services:10.0.0
    ports:
      - "21345:21345"
  kie-webapp:
    image: docker.io/apache/incubator-kie-sandbox-webapp:10.0.0
    ports:
      - "8080:8080"
  kafka:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda
    command: >
      redpanda start
      --overprovisioned
      --smp 1
      --memory 1G
      --reserve-memory 0M
      --node-id 0
      --check=false
      --kafka-addr PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
      --advertise-kafka-addr PLAINTEXT://redpanda:9092,OUTSIDE://localhost:19092
    ports:
      - "9092:9092" # Internal broker communication
      - "19092:19092" # External access for local clients
      - "9644:9644" # Admin API port
    environment:
      - REDPANDA_AUTO_CREATE_TOPICS=true
    restart: always
  
  kafka-ui:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda_console
    environment:
      - KAFKA_BROKERS=redpanda:9092
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    restart: always

